spring:
  application:
    name: Backend do sequeiraApp
    port: 8080
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/db_pedidosapp
    username: root
    password: Zefelipe22!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



jwt:
  secret: ${JWT_SECRET:chave-super-secreta-para-jwt-1234567890}